@extends('layouts.main')
@section('content')
   <div class="card">
            <div class="card-header">
                    <a href="#" class="btn  float-left  btn-xs" ><i class="fa fa-plus-circle" aria-hidden="true"></i> List of invoice</a>
            </div>
            <div class="card-body">
                Select invoice to see invoice  details
                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show">
                        <p>{{ $message }}</p>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <table class="table table-bordered table-striped table-sm">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Invoices</th>
                        <th>Generated by</th>
                        <th>Generated date</th>
                        <th>Statistical Officer Confirmation</th>
                        <th>Headmaster Confirmation</th>
                    </tr>
                    </thead>
                    @if($invoices->count() > 0)
                    <tbody>
                    @foreach ($invoices as $invoice)
                        <tr>
                                                        <td>{{ ++$i }}.</td>
                            <td><a href="{{ url('/schoolsInvoicesDetailsHead/get',$invoice->invoicerefnumber) }}">{{ $invoice->invoicerefnumber }}</a></td>
                            <td> {{ $invoice->projectmanager->user->email }}</td>
                            <td>  {{ $invoice->generated_date_by_proj }} </td>
                            @if($invoice->received_invoice_stat==0)
                                <td class="text-center"> - </td>
                            @else
                                <td>{{ $invoice->statisticalofficer->user->email }},<strong class="text-success"> Received date :</strong>  {{ $invoice->accepted_date_by_stat }} </td>
                            @endif

                            @if($invoice->received_invoice_stat==1)
                            @if($invoice->received_invoice_by_head==0)
                                <td><a href="{{ url('/schoolsInvoicesDetailsAccept/get',$invoice->invoicerefnumber) }}">- Accept</a></td>
                            @else
                                <td class="text-center">{{ $invoice->generated_date_by_ }}{{ $invoice->headmaster->user->email }}  <strong class="text-success"> Received date :</strong>  {{ $invoice->accepted_date_by_head }}</td>

                            @endif
                                @else
                                <td class="text-center"> - </td>
                            @endif

                        </tr>
                    @endforeach
                    @else
                        <tr >
                            <td colspan="7" class="text-center">No invoice created yet !!</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
@endsection

