@extends('layouts.main')
@section('content')
    <div class="card">
        <div class="card-header">
            <a href="#" class="btn  float-left  btn-xs" >Select Invoice for Details</a>
        </div>
        <div class="card-body">
            List of Invoices
            @if ($message = Session::get('success'))
                <div class="alert alert-success alert-dismissible fade show">
                    <p>{{ $message }}</p>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            @endif
            <table class="table table-bordered table-striped table-sm">
                @if($schools->count() > 0)     <thead>
                <tr>
                    {{--                        <th>#</th>--}}
                    <th>Invoices</th>

                    <th>Generated by</th>
                    <th>Generated date</th>
                    <th>Statistical Officer</th>
                    <th>Statistical Officer Confirmation </th>

                </tr>
                </thead>
                    <tbody>
                    @foreach ($schools as $invoice)
                        <tr>
                            {{--                            <td>{{ ++$i }}.</td>--}}
                            <td><a href="{{ url('/schoolsInvoices/get',$invoice->invoicerefnumber) }}">{{ $invoice->invoicerefnumber }}</a></td>

                            <td> {{ $invoice->projectmanager->user->email }}</td>
                            <td>  {{ $invoice->generated_date_by_proj }} </td>


                            @if($invoice->received_invoice_stat==0)
                                <td class="text-center"> - </td>
                            @else
                                <td>{{ $invoice->statisticalofficer->user->email }},<strong class="text-success"> Received date :</strong>  {{ $invoice->accepted_date_by_stat }} </td>
                            @endif

                            @if($invoice->received_invoice_stat==0)
                                <td><a href="{{ url('/councilInvoicesDetailsAccept/get',$invoice->invoicerefnumber) }}">Accept </a></td>
                            @else
                                <td class="text-success"> Accepted</td>
                            @endif


                        </tr>
                    @endforeach
                    @else
                        <tr >
                            <td colspan="9" class="text-center">No invoice Generated yet !!</td>
                        </tr>
                    @endif
                    </tbody>
            </table>
        </div>
    </div>
@endsection

